### ISSUE TITLE
IMPORTANTE - Formato de presentaciones, código QR y modelo de charla - Zona VIP Palacio de Congresos.

### ISSUE THREAD

**Issue by manuparra** [espsrc/databeers#30]
Hola a tod@s:
@javierpayaaguirre @ninesmp75 @fergunet @sgonzalezsilot @jmmunoz-kolokium @JJ @manuparra @neozizou @amorag @zehio245 @DraXus @Rms78 @franguerrero @emimartossanchez @antoniogamizbadger @ixakalabadie @mrcabellom

Estimados ponentes de DataBeers GRX edición IA

Aprovecho este correo para expresarle una vez más nuestro entusiasmo por poder contar con usted como ponente esta semana. El I Congreso de IA de Andalucía está resultando un éxito en cuanto a los números previos a su celebración. Contamos ya con 2000 inscritos y más de 100 ponencias.

Puede encontrar la agenda del auditorio principal, así como de todas las salas paralelas aquí: https://juntadeandalucia.es/congresoIA/

El espacio Databeers, que se celebrará en la Zona Circular (ver plano)  con una dinámica diferente, también tiene su agenda ( en horario de 12 a 14 y de 16 a 18 ambos días)  que puede consultar aquí: https://espsrc.github.io/databeers/

Comentarle que usted está inscrito de oficio como ponente, por lo que no habrá problema en que asista a cualquier charla, tanto el 22 como el 23, en cualquier franja horaria.

 En cuanto a la logística de cara a su ponencia es **muy IMPORTANTE** lo siguiente:

- 1)  El formato de las presentaciones es libre, pero hemos acordado con el congreso usar estas plantillas para la primera y la última diapositiva con el branding del congreso, nombre de presentacion y ponente. Aquí tenéis cada una para cada sesión vuestra, podeis buscaros y añadirlas (copiar y pegarlas en vuestras slides en PPT, google slides, etc). Aquí las plantillas y QRs: https://drive.google.com/drive/folders/1x-58gLhm4HVne1kfFQH3S7ZJJ889vbMu

- 2) Dentro de cada presentación veréis que hay un código QR que debéis incluir en vuestras diapositivas para que el público pueda escanearlo y pida cervezas, además tengamos datos de la tupla: presentación-cerveza :).

- 3) Recordad que el formato de charla debe ser lo más atractivo posible, incluyendo imágenes, GIFs animados graciosos, y que sea muy divertida en general. No se pueden incluir FÓRMULAS, etc.. Debes intentar llegar a todos los públicos. 

- 4) Si hacéis la presentación en google slides mucho mejor ya que podremos ponerlas en el equipo de presentación directamente. Si es PPTX, HTML, KeyNote o cualquier otro formato, si estáis unos minutos antes del inicio de sesión podemos probar que todo se ve bien. Llevaremos un Mac para proyectar todas las sesiones, pero si queréis llevar el vuestro, aseguraos que tenéis HDMI.

Le facilitamos también una pequeña plantilla recomendada, al menos, para la primera y la última slide, a fin de guardar cierta imagen de marca durante el desarrollo del Congreso.

Informarle que tiene acceso a la sala Vip durante todo el congreso, y acceso a los almuerzos a partir de las 14:30h, situada en la Planta 2 del Palacio de Congresos y Exposiciones de Granada.

Quedamos a su disposición para cualquier consulta adicional o necesidad que quiera hacernos llegar.

Dudas y preguntas de última hora: mparra [at] iaa.es

**Rafael Mata Sanchez**
_Responsable de Transformación Digital, Simplificación y Agilización Administrativa
Gabinete Estratégico en Granada
Agencia Digital de Andalucía_

**Comment by ldarriba** [comment]
Añado a @angelbadger 

Estimados ponentes de DataBeers GRX edición IA

Aprovecho este correo para expresarle una vez más nuestro entusiasmo por poder contar con usted como ponente esta semana. El I Congreso de IA de Andalucía está resultando un éxito en cuanto a los números previos a su celebración. Contamos ya con 2000 inscritos y más de 100 ponencias.

Puede encontrar la agenda del auditorio principal, así como de todas las salas paralelas aquí: https://juntadeandalucia.es/congresoIA/

El espacio Databeers, que se celebrará en la Zona Circular (ver plano) con una dinámica diferente, también tiene su agenda ( en horario de 12 a 14 y de 16 a 18 ambos días) que puede consultar aquí: https://espsrc.github.io/databeers/

Comentarle que usted está inscrito de oficio como ponente, por lo que no habrá problema en que asista a cualquier charla, tanto el 22 como el 23, en cualquier franja horaria.

En cuanto a la logística de cara a su ponencia es muy IMPORTANTE lo siguiente:

El formato de las presentaciones es libre, pero hemos acordado con el congreso usar estas plantillas para la primera y la última diapositiva con el branding del congreso, nombre de presentacion y ponente. Aquí tenéis cada una para cada sesión vuestra, podeis buscaros y añadirlas (copiar y pegarlas en vuestras slides en PPT, google slides, etc). Aquí las plantillas y QRs: https://drive.google.com/drive/folders/1x-58gLhm4HVne1kfFQH3S7ZJJ889vbMu
Dentro de cada presentación veréis que hay un código QR que debéis incluir en vuestras diapositivas para que el público pueda escanearlo y pida cervezas, además tengamos datos de la tupla: presentación-cerveza :).
Recordad que el formato de charla debe ser lo más atractivo posible, incluyendo imágenes, GIFs animados graciosos, y que sea muy divertida en general. No se pueden incluir FÓRMULAS, etc.. Debes intentar llegar a todos los públicos.
Si hacéis la presentación en google slides mucho mejor ya que podremos ponerlas en el equipo de presentación directamente. Si es PPTX, HTML, KeyNote o cualquier otro formato, si estáis unos minutos antes del inicio de sesión podemos probar que todo se ve bien. Llevaremos un Mac para proyectar todas las sesiones, pero si queréis llevar el vuestro, aseguraos que tenéis HDMI.
Le facilitamos también una pequeña plantilla recomendada, al menos, para la primera y la última slide, a fin de guardar cierta imagen de marca durante el desarrollo del Congreso.

Informarle que tiene acceso a la sala Vip durante todo el congreso, y acceso a los almuerzos a partir de las 14:30h, situada en la Planta 2 del Palacio de Congresos y Exposiciones de Granada.

Quedamos a su disposición para cualquier consulta adicional o necesidad que quiera hacernos llegar.

Dudas y preguntas de última hora: mparra [at] iaa.es

Rafael Mata Sanchez
Responsable de Transformación Digital, Simplificación y Agilización Administrativa
Gabinete Estratégico en Granada
Agencia Digital de Andalucía

**Comment by ldarriba** [comment]
@javierpayaaguirre @ninesmp75 @fergunet @sgonzalezsilot @jmmunoz-kolokium @JJ @manuparra @neozizou @amorag @zehio245 @DraXus @franguerrero @emimartossanchez @antoniogamizbadger @ixakalabadie @mrcabellom @angelbadger 

Algunos habéis preguntado si las charlas deben ser en castellano o inglés, mejor que sean en castellano aunque podéis dejar las slides en inglés si os es más cómodo.

**Comment by mrcabellom** [comment]
Hola,

¿Qué tal? Por un tema de última hora el jueves 23 tengo que estar en el
auditorio en la charla de m🤣Moises weber de 12:30 a 13:00 porque tengo que
manejar al perro robot Spot.   Se que mi charla está en la franja de 12 a
14. ¿Habría algún problema en que me ausente esa media hora? Luego me
traigo al perro a la zona de databeers. 😊

Saludos y disculpad las molestias.

**Comment by JJ** [comment]
El mié, 22 nov 2023 a las 7:51, mrcabellom ***@***.***>)
escribió:

> Hola,
>
> ¿Qué tal? Por un tema de última hora el jueves 23 tengo que estar en el
> auditorio en la charla de m🤣Moises weber de 12:30 a 13:00 porque tengo
> que
> manejar al perro robot Spot. Se que mi charla está en la franja de 12 a
> 14. ¿Habría algún problema en que me ausente esa media hora? Luego me
> traigo al perro a la zona de databeers. 😊


No, ¿por qué va a haberlo? Se reorganizan las charlas si es necesario, es
cuestión de verlo sobre la marcha (o lo vemos ahora)
